### ISSUE TITLE
No module named 'folder_paths'

### ISSUE THREAD

**Issue by DefinitlyEvil** [SeargeDP/SeargeSDXL#100]
Any help would be appreciated! 
```
Traceback (most recent call last):
  File "...\ComfyUI\nodes.py", line 1002, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "...\ComfyUI\custom_nodes\SeargeSDXL\__init__.py", line 31, in <module>
    import folder_paths
ModuleNotFoundError: No module named 'folder_paths'
```

Latest nightly built ComfyUI, latest release branch of SeargeSDXL.

**Comment by SeargeDP** [comment]
Looks like something's not installed properly. `folder_paths` is an essential part of ComfyUI and without the file ComfyUI would not work at all. Try re-installing if nothing else works.

**Comment by DefinitlyEvil** [comment]
> Looks like something's not installed properly. `folder_paths` is an essential part of ComfyUI and without the file ComfyUI would not work at all. Try re-installing if nothing else works.

Hi thanks for your reply, I tried with a older version and it worked!
