### ISSUE TITLE
Error Importing : module 'cv2.gapi.wip.draw' has no attribute 'Text'

### ISSUE THREAD

**Issue by c4alex** [SeargeDP/SeargeSDXL#106]
Hello !

Trying to solve this issue since few hours :

```
### Loading: ComfyUI-Manager (V1.0.1)
### ComfyUI Revision: 1688 [728613bb] | Released on '2023-11-14'
Total VRAM 12287 MB, total RAM 65452 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync
VAE dtype: torch.bfloat16
Torch version: 2.1.1+cu118
Searge-SDXL v4.3.1 in C:\STABLE DIFFUSION COMFY UI PORTABLE\ComfyUI\custom_nodes\SeargeSDXL
Traceback (most recent call last):
  File "C:\STABLE DIFFUSION COMFY UI PORTABLE\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\STABLE DIFFUSION COMFY UI PORTABLE\ComfyUI\custom_nodes\SeargeSDXL\__init__.py", line 35, in <module>
    from .searge_sdxl import SEARGE_CLASS_MAPPINGS, SEARGE_DISPLAY_NAME_MAPPINGS
  File "C:\STABLE DIFFUSION COMFY UI PORTABLE\ComfyUI\custom_nodes\SeargeSDXL\searge_sdxl.py", line 32, in <module>
    from .modules.controlnet_adapter import SeargeControlnetAdapterV2
  File "C:\STABLE DIFFUSION COMFY UI PORTABLE\ComfyUI\custom_nodes\SeargeSDXL\modules\controlnet_adapter.py", line 31, in <module>
    from .controlnet import canny
  File "C:\STABLE DIFFUSION COMFY UI PORTABLE\ComfyUI\custom_nodes\SeargeSDXL\modules\controlnet\__init__.py", line 4, in <module>
    from .canny import CannyDetector
  File "C:\STABLE DIFFUSION COMFY UI PORTABLE\ComfyUI\custom_nodes\SeargeSDXL\modules\controlnet\canny\__init__.py", line 2, in <module>
    import cv2
  File "C:\STABLE DIFFUSION COMFY UI PORTABLE\python_embeded\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\STABLE DIFFUSION COMFY UI PORTABLE\python_embeded\lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "C:\STABLE DIFFUSION COMFY UI PORTABLE\python_embeded\lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "importlib\__init__.py", line 126, in import_module
  File "C:\STABLE DIFFUSION COMFY UI PORTABLE\python_embeded\lib\site-packages\cv2\typing\__init__.py", line 157, in <module>
    Prim = typing.Union[cv2.gapi.wip.draw.Text, cv2.gapi.wip.draw.Circle, cv2.gapi.wip.draw.Image, cv2.gapi.wip.draw.Line, cv2.gapi.wip.draw.Rect, cv2.gapi.wip.draw.Mosaic, cv2.gapi.wip.draw.Poly]
AttributeError: module 'cv2.gapi.wip.draw' has no attribute 'Text'

Cannot import C:\STABLE DIFFUSION COMFY UI PORTABLE\ComfyUI\custom_nodes\SeargeSDXL module for custom nodes: module 'cv2.gapi.wip.draw' has no attribute 'Text'

```

I've been trying to solve this problem for a few hours but I really can't find...

I'm not a python expert by any means, but I've tried everything I could think of:

- Uninstall opencv-python and Install a previous version
- Manually remove opencv/cv2 from the packages folder
- Manual installation of SeargeSDXL
- Install with SeargeSDXL-Installer.bat
- tested update_comfyui.bat
- tested update_comfyui_and_python_dependencies.bat
- cleaned local PIP cache
- checked that I'm in embedded python

I have another script that gives me the same kind of error when I activate it, all the others work perfectly, maybe this is a lead, if anyone has an idea, I'm interested!

> Thanks for reading!

**Comment by c4alex** [comment]
Hello Again, I finally solved my issue by installing this version of opencv-python (emmbeded) :

opencv_python-4.5.5.64

Hope that helps others.. !
