### ISSUE TITLE
failed to load seargesdxl

### ISSUE THREAD

**Issue by moviejimmy** [SeargeDP/SeargeSDXL#108]
ERROR:

Total VRAM 24564 MB, total RAM 65277 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### ComfyUI Revision: 1712 [72741105] | Released on '2023-11-21'
Total VRAM 24564 MB, total RAM 65277 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Torch version: 2.1.0+cu121
Searge-SDXL v4.3.1 in C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1784, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\__init__.py", line 35, in <module>
    from .searge_sdxl import SEARGE_CLASS_MAPPINGS, SEARGE_DISPLAY_NAME_MAPPINGS
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\searge_sdxl.py", line 32, in <module>
    from .modules.controlnet_adapter import SeargeControlnetAdapterV2
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\controlnet_adapter.py", line 31, in <module>
    from .controlnet import canny
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\controlnet\__init__.py", line 4, in <module>
    from .canny import CannyDetector
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\controlnet\canny\__init__.py", line 2, in <module>
    import cv2
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2\typing\__init__.py", line 157, in <module>
    Prim = typing.Union[cv2.gapi.wip.draw.Text, cv2.gapi.wip.draw.Circle, cv2.gapi.wip.draw.Image, cv2.gapi.wip.draw.Line, cv2.gapi.wip.draw.Rect, cv2.gapi.wip.draw.Mosaic, cv2.gapi.wip.draw.Poly]
                        ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'cv2.gapi.wip.draw' has no attribute 'Text'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL module for custom nodes: module 'cv2.gapi.wip.draw' has no attribute 'Text'

Import times for custom nodes:
   0.1 seconds (IMPORT FAILED): C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL

**Comment by moviejimmy** [comment]
Would appreciate some help here. No idea what went wrong. I installed via the .bat file. Everything went smoothly without errors during installation.

**Comment by moviejimmy** [comment]
In case this is relevant, I have these installed:

opencv-contrib-python         4.5.5.64
opencv-python                 4.8.1.78
opencv-python-headless        4.7.0.72

**Comment by moviejimmy** [comment]
I also tried this:

pip uninstall -y opencv-python opencv-contrib-python opencv-python-headless 
pip install opencv-python==4.7.0.72

But it didn't work. Same error.

**Comment by SeargeDP** [comment]
I can't reproduce this problem here, using the latest version of ComfyUI and the latest version of my node extension. But I noticed that the only opencv package I have installed here is `opencv-python` version `4.8.1.78`

**Comment by badiolac** [comment]
I had a similar problem with Comfy-Impact-Pack.
I uninstalled like you did @moviejimmy, and then I installed a specific version of opencv, see [troobleshooting](https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md#an-issue-has-occurred-about-cv2).
