### ISSUE TITLE
AttributeError: 'ModelPatcher' object has no attribute 'memory_required'

### ISSUE THREAD

**Issue by GrosFumiste** [SeargeDP/SeargeSDXL#120]
ERROR:root:Traceback (most recent call last):
  File "S:\Comfy\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "S:\Comfy\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "S:\Comfy\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "S:\Comfy\ComfyUI\custom_nodes\SeargeSDXL\modules\magic_box.py", line 269, in process
    (data, stage_result) = self.run_stage(stage, data, stage_input)
  File "S:\Comfy\ComfyUI\custom_nodes\SeargeSDXL\modules\magic_box.py", line 248, in run_stage
    (data, stage_result) = stage_processor.process(data, stage_input)
  File "S:\Comfy\ComfyUI\custom_nodes\SeargeSDXL\modules\stage_sampling.py", line 126, in process
    latent = sampler(base_model, base_positive, base_negative, latent, seed, steps, cfg,
  File "S:\Comfy\ComfyUI\custom_nodes\SeargeSDXL\modules\node_wrapper.py", line 99, in sdxl_sampler
    result = sdxl_ksampler(base_model, refiner_model, noise_seed, base_steps, refiner_steps, cfg, sampler_name,
  File "S:\Comfy\ComfyUI\custom_nodes\SeargeSDXL\modules\custom_sdxl_ksampler.py", line 356, in sdxl_ksampler
    samples = sdxl_sample(base_model, refiner_model, noise, base_steps, refiner_steps, cfg, sampler_name, scheduler,
  File "S:\Comfy\ComfyUI\custom_nodes\SeargeSDXL\modules\custom_sdxl_ksampler.py", line 174, in sdxl_sample
    memory_required = base_model.memory_required(noise.shape) + inference_memory
AttributeError: 'ModelPatcher' object has no attribute 'memory_required'

**Comment by SeargeDP** [comment]
Are you using the latest version of ComfyUI?
