### ISSUE TITLE
No module named 'comfy_extras.nodes_freelunch'

### ISSUE THREAD

**Issue by Tartarians** [SeargeDP/SeargeSDXL#125]
Hi, 
I am using linux.
I followed the guide. I already fix some issues but still have that one : 

Searge-SDXL v4.3.1 in /home/polychromatik/Applications/ComfyUI/custom_nodes/SeargeSDXL
Traceback (most recent call last):
File "/home/polychromatik/Applications/ComfyUI/nodes.py", line 1725, in load_custom_node
module_spec.loader.exec_module(module)
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/home/polychromatik/Applications/ComfyUI/custom_nodes/SeargeSDXL/__init__.py", line 35, in <module>
from .searge_sdxl import SEARGE_CLASS_MAPPINGS, SEARGE_DISPLAY_NAME_MAPPINGS
File "/home/polychromatik/Applications/ComfyUI/custom_nodes/SeargeSDXL/searge_sdxl.py", line 54, in <module>
from .modules.magic_box import SeargeMagicBox
File "/home/polychromatik/Applications/ComfyUI/custom_nodes/SeargeSDXL/modules/magic_box.py", line 31, in <module>
from .stage_pre_processing import SeargePreProcessData
File "/home/polychromatik/Applications/ComfyUI/custom_nodes/SeargeSDXL/modules/stage_pre_processing.py", line 33, in <module>
from .node_wrapper import NodeWrapper
File "/home/polychromatik/Applications/ComfyUI/custom_nodes/SeargeSDXL/modules/node_wrapper.py", line 34, in<module>
import comfy_extras.nodes_freelunch
ModuleNotFoundError: No module named 'comfy_extras.nodes_freelunch'

Cannot import /home/polychromatik/Applications/ComfyUI/custom_nodes/SeargeSDXL module for custom nodes: No module named 'comfy_extras.nodes_freelunch'

Import times for custom nodes:
0.0 seconds: /home/polychromatik/Applications/ComfyUI/custom_nodes/ComfyUI-Manager
0.0 seconds (IMPORT FAILED): /home/polychromatik/Applications/ComfyUI/custom_nodes/SeargeSDXL
0.1 seconds: /home/polychromatik/Applications/ComfyUI/custom_nodes/comfyui_milehighstyler
0.2 seconds: /home/polychromatik/Applications/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
0.5 seconds: /home/polychromatik/Applications/ComfyUI/custom_nodes/was-node-suite-comfyui
0.6 seconds: /home/polychromatik/Applications/ComfyUI/custom_nodes/was-node-suite-comfyui-main

**Comment by SeargeDP** [comment]
Please update ComfyUI to the latest version, this error is caused by using an older version of Comfy that didn't have FreeU support included already.

**Comment by Tartarians** [comment]
Awesome, it's working now :+1: 
Thank you so much @SeargeDP
