### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by hunt3rx02** [SeargeDP/SeargeSDXL#129]
Is there a way to install your package on ComfyUI (by Stability Matrix), because it doesn't work. It's "import failed". 

I'm sending you the lines of code from my Stability Matrix console.
```

**> 
> ------------------------------------------
> Comfyroll Studio v1.68 :  170 Nodes Loaded
> ------------------------------------------
> ** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
> ** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
> ------------------------------------------
> Searge-SDXL v4.3.1 in C:\Users\Quentin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\SeargeSDXL
> Traceback (most recent call last):
>   File "C:\Users\Quentin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\nodes.py", line 1872, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "C:\Users\Quentin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\SeargeSDXL\__init__.py", line 35, in <module>
>     from .searge_sdxl import SEARGE_CLASS_MAPPINGS, SEARGE_DISPLAY_NAME_MAPPINGS
>   File "C:\Users\Quentin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\SeargeSDXL\searge_sdxl.py", line 32, in <module>
>     from .modules.controlnet_adapter import SeargeControlnetAdapterV2
>   File "C:\Users\Quentin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\SeargeSDXL\modules\controlnet_adapter.py", line 31, in <module>
>     from .controlnet import canny
>   File "C:\Users\Quentin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\SeargeSDXL\modules\controlnet\__init__.py", line 4, in <module>
>     from .canny import CannyDetector
>   File "C:\Users\Quentin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\SeargeSDXL\modules\controlnet\canny\__init__.py", line 2, in <module>
>     import cv2
> ModuleNotFoundError: No module named 'cv2'
> 
> Cannot import C:\Users\Quentin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\SeargeSDXL module for custom nodes: No module named 'cv2'
> 
> Import times for custom nodes:
>    0.4 seconds: C:\Users\Quentin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Manager
>    0.6 seconds (IMPORT FAILED): C:\Users\Quentin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\SeargeSDXL
>   12.3 seconds: C:\Users\Quentin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
> 
> Starting server
>** 

```

**Comment by bishopZ** [comment]
`pip install opencv-python` solved it for me.
