### ISSUE TITLE
ImportError: cannot import name 'prepare_mask'

### ISSUE THREAD

**Issue by taconugget** [SeargeDP/SeargeSDXL#136]
With the latest update to Comfy it's reporting the following error and will not load:

   0.1 seconds (IMPORT FAILED): /home/zvi/ComfyUI/custom_nodes/SeargeSDXL

`Searge-SDXL v4.3.1 in /home/zvi/ComfyUI/custom_nodes/SeargeSDXL
Traceback (most recent call last):
  File "/home/zvi/ComfyUI/nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/zvi/ComfyUI/custom_nodes/SeargeSDXL/__init__.py", line 35, in <module>
    from .searge_sdxl import SEARGE_CLASS_MAPPINGS, SEARGE_DISPLAY_NAME_MAPPINGS
  File "/home/zvi/ComfyUI/custom_nodes/SeargeSDXL/searge_sdxl.py", line 54, in <module>
    from .modules.magic_box import SeargeMagicBox
  File "/home/zvi/ComfyUI/custom_nodes/SeargeSDXL/modules/magic_box.py", line 38, in <module>
    from .stage_latent_detailer import SeargeStageLatentDetailer
  File "/home/zvi/ComfyUI/custom_nodes/SeargeSDXL/modules/stage_latent_detailer.py", line 29, in <module>
    from comfy.sample import prepare_mask
ImportError: cannot import name 'prepare_mask' from 'comfy.sample' (/home/zvi/ComfyUI/comfy/sample.py)

Cannot import /home/zvi/ComfyUI/custom_nodes/SeargeSDXL module for custom nodes: cannot import name 'prepare_mask' from 'comfy.sample' (/home/zvi/ComfyUI/comfy/sample.py)`

**Comment by jundao17** [comment]
easy fix
Error: from comfy.sample import prepare_mask 
Fixed: from comfy.sampler_helpers import prepare_mask

**Comment by makeitrad** [comment]
Thanks for the fix!
