### ISSUE TITLE
One of the more recent updates have broken SeargeSDXL nodes and it fails to load.

### ISSUE THREAD

**Issue by axdwct** [SeargeDP/SeargeSDXL#137]
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\ComfyUI\ComfyUI\nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ProgramData\anaconda3\envs\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL\__init__.py", line 35, in <module>
    from .searge_sdxl import SEARGE_CLASS_MAPPINGS, SEARGE_DISPLAY_NAME_MAPPINGS
  File "C:\ProgramData\anaconda3\envs\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL\searge_sdxl.py", line 54, in <module>
    from .modules.magic_box import SeargeMagicBox
  File "C:\ProgramData\anaconda3\envs\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL\modules\magic_box.py", line 38, in <module>
    from .stage_latent_detailer import SeargeStageLatentDetailer
  File "C:\ProgramData\anaconda3\envs\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL\modules\stage_latent_detailer.py", line 29, in <module>
    from comfy.sample import prepare_mask
ImportError: cannot import name 'prepare_mask' from 'comfy.sample' (C:\ProgramData\anaconda3\envs\ComfyUI\ComfyUI\comfy\sample.py)

**Comment by MicPec** [comment]
Same here:

Searge-SDXL v4.3.1 in /run/media/AI/StabilityMatrix-linux-x64/Data/Packages/ComfyUI/custom_nodes/SeargeSDXL
Traceback (most recent call last):
  File "/run/media/AI/StabilityMatrix-linux-x64/Data/Packages/ComfyUI/nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/run/media/AI/StabilityMatrix-linux-x64/Data/Packages/ComfyUI/custom_nodes/SeargeSDXL/__init__.py", line 35, in <module>
    from .searge_sdxl import SEARGE_CLASS_MAPPINGS, SEARGE_DISPLAY_NAME_MAPPINGS
  File "/run/media/AI/StabilityMatrix-linux-x64/Data/Packages/ComfyUI/custom_nodes/SeargeSDXL/searge_sdxl.py", line 54, in <module>
    from .modules.magic_box import SeargeMagicBox
  File "/run/media/AI/StabilityMatrix-linux-x64/Data/Packages/ComfyUI/custom_nodes/SeargeSDXL/modules/magic_box.py", line 38, in <module>
    from .stage_latent_detailer import SeargeStageLatentDetailer
  File "/run/media/AI/StabilityMatrix-linux-x64/Data/Packages/ComfyUI/custom_nodes/SeargeSDXL/modules/stage_latent_detailer.py", line 29, in <module>
    from comfy.sample import prepare_mask
ImportError: cannot import name 'prepare_mask' from 'comfy.sample' (/run/media/AI/StabilityMatrix-linux-x64/Data/Packages/ComfyUI/comfy/sample.py)

Cannot import /run/media/AI/StabilityMatrix-linux-x64/Data/Packages/ComfyUI/custom_nodes/SeargeSDXL module for custom nodes: cannot import name 'prepare_mask' from 'comfy.sample' (/run/media/AI/StabilityMatrix-linux-x64/Data/Packages/ComfyUI/comfy/sample.py)

**Comment by Arron17** [comment]
Some of the Comfy sample settings have been moved.

in the file "SeargeSDXL\Modules\stage_latent_detailer.py" at line 29 change

from comfy.sample import prepare_mask

to

from comfy.sampler_helpers import prepare_mask

That should fix it.

**Comment by jobunk** [comment]
@Arron17 This fix works for loading the modules. However custom_sdxl_ksampler.py also got broken by these changes, but the error only occurs when actually trying to run the SDLX Sampler v3 module. I tried some quick fixes that just led to errors in different places, so for now I went with a temporary solution:
Instead of adjusting SeargeSDXL you can edit the sample.py and sampler.py and revert them to older versions.
https://github.com/comfyanonymous/ComfyUI/blob/977eda19a6471fbff253dc92c3c2f1a4a67b1793/comfy/sample.py
https://github.com/comfyanonymous/ComfyUI/blob/e6482fbbfc83cd25add0532b2e4c51d305e8a232/comfy/samplers.py

Obviously this fix is very temporary and will eventually stop working, so changes to SeargeSDXL are definitely needed.

**Comment by jeffyspoke** [comment]
> @Arron17 This fix works for loading the modules. However custom_sdxl_ksampler.py also got broken by these changes, but the error only occurs when actually trying to run the SDLX Sampler v3 module. I tried some quick fixes that just led to errors in different places, so for now I went with a temporary solution: Instead of adjusting SeargeSDXL you can edit the sample.py and sampler.py and revert them to older versions. https://github.com/comfyanonymous/ComfyUI/blob/977eda19a6471fbff253dc92c3c2f1a4a67b1793/comfy/sample.py https://github.com/comfyanonymous/ComfyUI/blob/e6482fbbfc83cd25add0532b2e4c51d305e8a232/comfy/samplers.py
> 
> Obviously this fix is very temporary and will eventually stop working, so changes to SeargeSDXL are definitely needed.

This fixed it for me - thank you

**Comment by bitshifter52** [comment]
This happened in a Debian environment:

<code>
_Trying to load custom node /media/drives/16TB/ComfyUI/custom_nodes/SeargeSDXL
Searge-SDXL v4.3.1 in /media/drives/16TB/ComfyUI/custom_nodes/SeargeSDXL
Traceback (most recent call last):
  File "/media/drives/16TB/ComfyUI/nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/media/drives/16TB/ComfyUI/custom_nodes/SeargeSDXL/__init__.py", line 35, in <module>
    from .searge_sdxl import SEARGE_CLASS_MAPPINGS, SEARGE_DISPLAY_NAME_MAPPINGS
  File "/media/drives/16TB/ComfyUI/custom_nodes/SeargeSDXL/searge_sdxl.py", line 54, in <module>
    from .modules.magic_box import SeargeMagicBox
  File "/media/drives/16TB/ComfyUI/custom_nodes/SeargeSDXL/modules/magic_box.py", line 38, in <module>
    from .stage_latent_detailer import SeargeStageLatentDetailer
  File "/media/drives/16TB/ComfyUI/custom_nodes/SeargeSDXL/modules/stage_latent_detailer.py", line 29, in <module>
    from comfy.sample import prepare_mask
ImportError: cannot import name 'prepare_mask' from 'comfy.sample' (/media/drives/16TB/ComfyUI/comfy/sample.py)

Cannot import /media/drives/16TB/ComfyUI/custom_nodes/SeargeSDXL module for custom nodes: cannot import name 'prepare_mask' from 'comfy.sample' (/media/drives/16TB/ComfyUI/comfy/sample.py)_
</code>

Will try the above mentioned work-arounds.

**Comment by jobunk** [comment]
I managed to fix the errors caused by the changes to sample.py etc:
https://github.com/jobunk/SeargeSDXL/commit/9d11b6dcf4ae8ed3a4060b80ed29098f9f30b618. 

However there was another recent change that I don't know how to deal with. Relevant commit:
https://github.com/comfyanonymous/ComfyUI/commit/1a0486bb96fb1ff10f4ea3c0d62eb815e9630585

Another user also reported running into errors regarding this change, so let's see if will be resolved
https://github.com/comfyanonymous/ComfyUI/issues/3217

**Comment by mskiller** [comment]
I commented out the line 29 of stage_latent_detailer.py , it let searge loads as module, and I could get back my workflow running. but not sure it will not run into some issue later.

**Comment by hashmil** [comment]
> @Arron17 This fix works for loading the modules. However custom_sdxl_ksampler.py also got broken by these changes, but the error only occurs when actually trying to run the SDLX Sampler v3 module. I tried some quick fixes that just led to errors in different places, so for now I went with a temporary solution: Instead of adjusting SeargeSDXL you can edit the sample.py and sampler.py and revert them to older versions. https://github.com/comfyanonymous/ComfyUI/blob/977eda19a6471fbff253dc92c3c2f1a4a67b1793/comfy/sample.py https://github.com/comfyanonymous/ComfyUI/blob/e6482fbbfc83cd25add0532b2e4c51d305e8a232/comfy/samplers.py
> 
> Obviously this fix is very temporary and will eventually stop working, so changes to SeargeSDXL are definitely needed.

this broke my comfy somewhat:

```
Traceback (most recent call last):
  File "/Users/hash.milhan/ComfyUI/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/hash.milhan/ComfyUI/comfy_extras/nodes_custom_sampler.py", line 386, in <module>
    class Guider_Basic(comfy.samplers.CFGGuider):
                       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'comfy.samplers' has no attribute 'CFGGuider'
```

**Comment by jobunk** [comment]
I have am open PR that should fix everything described here. Just get the newest version of confyUI and this module and then adjust the files changed in my PR. https://github.com/SeargeDP/SeargeSDXL/pull/140

The last change to this repo was 5 months ago so I don't know how fast my PR will be merged.
