### ISSUE TITLE
New ComfUI Update broke your Node.

### ISSUE THREAD

**Issue by Piscabo** [SeargeDP/SeargeSDXL#142]
Is there a fix on the way?
ComfyUI Revision: 2115 [0a030098] | Released on '2024-04-06'

Searge-SDXL v4.3.1 in H:\ComfyUI\custom_nodes\SeargeSDXL
Traceback (most recent call last):
  File "H:\ComfyUI\nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI\custom_nodes\SeargeSDXL\__init__.py", line 35, in <module>
    from .searge_sdxl import SEARGE_CLASS_MAPPINGS, SEARGE_DISPLAY_NAME_MAPPINGS
  File "H:\ComfyUI\custom_nodes\SeargeSDXL\searge_sdxl.py", line 54, in <module>
    from .modules.magic_box import SeargeMagicBox
  File "H:\ComfyUI\custom_nodes\SeargeSDXL\modules\magic_box.py", line 38, in <module>
    from .stage_latent_detailer import SeargeStageLatentDetailer
  File "H:\ComfyUI\custom_nodes\SeargeSDXL\modules\stage_latent_detailer.py", line 29, in <module>
    from comfy.sample import prepare_mask
ImportError: cannot import name 'prepare_mask' from 'comfy.sample' (H:\ComfyUI\comfy\sample.py)

Cannot import H:\ComfyUI\custom_nodes\SeargeSDXL module for custom nodes: cannot import name 'prepare_mask' from 'comfy.sample' (H:\ComfyUI\comfy\sample.py)

**Comment by hashmil** [comment]
i'm having the same issue! 

```
Searge-SDXL v4.3.1 in /Users/hash.milhan/ComfyUI/custom_nodes/SeargeSDXL
Traceback (most recent call last):
  File "/Users/hash.milhan/ComfyUI/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/hash.milhan/ComfyUI/custom_nodes/SeargeSDXL/__init__.py", line 35, in <module>
    from .searge_sdxl import SEARGE_CLASS_MAPPINGS, SEARGE_DISPLAY_NAME_MAPPINGS
  File "/Users/hash.milhan/ComfyUI/custom_nodes/SeargeSDXL/searge_sdxl.py", line 54, in <module>
    from .modules.magic_box import SeargeMagicBox
  File "/Users/hash.milhan/ComfyUI/custom_nodes/SeargeSDXL/modules/magic_box.py", line 38, in <module>
    from .stage_latent_detailer import SeargeStageLatentDetailer
  File "/Users/hash.milhan/ComfyUI/custom_nodes/SeargeSDXL/modules/stage_latent_detailer.py", line 29, in <module>
    from comfy.sample import prepare_mask
ImportError: cannot import name 'prepare_mask' from 'comfy.sample' (/Users/hash.milhan/ComfyUI/comfy/sample.py)

Cannot import /Users/hash.milhan/ComfyUI/custom_nodes/SeargeSDXL module for custom nodes: cannot import name 'prepare_mask' from 'comfy.sample' (/Users/hash.milhan/ComfyUI/comfy/sample.py)
```

**Comment by huwhitememes** [comment]
This is what happened to me also 😢

**Comment by oktetopython** [comment]
Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL\__init__.py", line 35, in <module>
    from .searge_sdxl import SEARGE_CLASS_MAPPINGS, SEARGE_DISPLAY_NAME_MAPPINGS
  File "H:\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL\searge_sdxl.py", line 54, in <module>
    from .modules.magic_box import SeargeMagicBox
  File "H:\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL\modules\magic_box.py", line 38, in <module>
    from .stage_latent_detailer import SeargeStageLatentDetailer
  File "H:\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL\modules\stage_latent_detailer.py", line 29, in <module>
    from comfy.sample import prepare_mask
ImportError: cannot import name 'prepare_mask' from 'comfy.sample' (H:\ComfyUI\ComfyUI\comfy\sample.py)

Cannot import H:\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL module for custom nodes: cannot import name 'prepare_mask' from 'comfy.sample' (H:\ComfyUI\ComfyUI\comfy\sample.py)

**Comment by hashmil** [comment]
this PR is supposed to fix it - https://github.com/SeargeDP/SeargeSDXL/pull/140

**Comment by 0xcyph** [comment]
any updates? : ) cant use any LCM rn  : (

**Comment by stephantual** [comment]
it's fixed now, thank you
