### ISSUE TITLE
'Namespace' object has no attribute 'disable_metadata'

### ISSUE THREAD

**Issue by suteerth** [SeargeDP/SeargeSDXL#20]
Running text2image using the provided workflow throws this error.

Stacktrace:

```
DDIM Sampler: 100%|██████████████████████████████████████████████████████████████████████| 6/6 [00:01<00:00,  3.42it/s]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\Users\sutir\comfyui\ComfyUI\execution.py", line 144, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\sutir\comfyui\ComfyUI\execution.py", line 74, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\sutir\comfyui\ComfyUI\execution.py", line 67, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\sutir\comfyui\ComfyUI\custom_nodes\SeargeSDXL\searge_sdxl_sampler_node.py", line 631, in save_images
    if not args.disable_metadata:
AttributeError: 'Namespace' object has no attribute 'disable_metadata'
```

**Comment by DawidIzydor** [comment]
Getting the same error
`Error occurred when executing SeargeImageSave:

'Namespace' object has no attribute 'disable_metadata'

  File "D:\Source\superstable-diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 144, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\Source\superstable-diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\Source\superstable-diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 67, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\Source\superstable-diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\searge_sdxl_sampler_node.py", line 640, in save_images
    if not args.disable_metadata:`

**Comment by DawidIzydor** [comment]
Commenting out the line containing disable_metadata and modyfing the intendation seems to be a dirty fix
``` python
            #if not args.disable_metadata:
            metadata = PngInfo()
            if prompt is not None:
                metadata.add_text("prompt", json.dumps(prompt))
            if extra_pnginfo is not None:
                for x in extra_pnginfo:
                    metadata.add_text(x, json.dumps(extra_pnginfo[x]))
```

**Comment by SeargeDP** [comment]
please let me know if this is still an issue in version 3.1 (just released)

**Comment by SeargeDP** [comment]
Also, are you using the latest version of ComfyUI?

**Comment by suteerth** [comment]
Working after the latest fix, closing this issue

**Comment by w0nche0l** [comment]
weird, i'm still getting this error on the latest version of SeargeSDXL.: 
Does anyone know how to check the version of ComfyUI / update to the latest? 

Traceback (most recent call last):
  File "C:\Users\wonje\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 145, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\wonje\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\wonje\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\wonje\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\searge_sdxl_sampler_node.py", line 361, in save_images
    if args.disable_metadata is None or not args.disable_metadata:
AttributeError: 'Namespace' object has no attribute 'disable_metadata'

**Comment by DawidIzydor** [comment]
Still getting the same issue on 3.4 

```
  File "D:\Source\superstable-diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 144, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\Source\superstable-diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\Source\superstable-diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 67, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\Source\superstable-diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\searge_sdxl_sampler_node.py", line 361, in save_images
    if args.disable_metadata is None or not args.disable_metadata:
AttributeError: 'Namespace' object has no attribute 'disable_metadata'
```

**Comment by SeargeDP** [comment]
You need to update ComfyUI to the latest version
