### ISSUE TITLE
SyntaxError when launching

### ISSUE THREAD

**Issue by 49RpK5dY** [SeargeDP/SeargeSDXL#24]
The extension fails to import since https://github.com/SeargeDP/SeargeSDXL/commit/8f591495cc986e2f7528d1334e95dfc2c6511dc9. Getting this
```
Traceback (most recent call last):
  File "/sd/ComfyUI/nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/sd/ComfyUI/custom_nodes/SeargeSDXL/__init__.py", line 1, in <module>
    from .searge_sdxl_sampler_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/sd/ComfyUI/custom_nodes/SeargeSDXL/searge_sdxl_sampler_node.py", line 615
    match save_to:
          ^
SyntaxError: invalid syntax

Cannot import /sd/ComfyUI/custom_nodes/SeargeSDXL module for custom nodes: invalid syntax (searge_sdxl_sampler_node.py, line 615)
```
I'm running ComfyUI in a docker container with Python 3.9.5 on an amd card if that helps.

**Comment by SeargeDP** [comment]
Thanks for the feedback. Right now it's not compatible with python 3.9 and depends on 3.10, but I'll make some changes in the next update so it should work with 3.9 and 3.10 after that's released.

**Comment by 49RpK5dY** [comment]
Thanks. I really love some unique nodes and can't imagine a workflow without them. Would also like to check some of the new stuff.

**Comment by 49RpK5dY** [comment]
Works great after update. Thanks.
