### ISSUE TITLE
Inpainting Error: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by rivaldophilip** [SeargeDP/SeargeSDXL#35]
Would greatly appreciate help in resolving this!

MetadataIncompleteBuffer error when using SDXL with Google Colab (A100 and T4)

Prompt mode: Simple, inpainting

Models used:
https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0_0.9vae.safetensors
https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/resolve/main/sd_xl_refiner_1.0_0.9vae.safetensors
https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/resolve/main/sdxl_vae.safetensors
https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_offset_example-lora_1.0.safetensors (strength was put to 0 so should be off)
https://huggingface.co/sberbank-ai/Real-ESRGAN/resolve/main/RealESRGAN_x4.pth (though not connected)

Workflow (based on SeargeSDXL 3.4):
[workflow.zip](https://github.com/SeargeDP/SeargeSDXL/files/12316940/workflow.zip)

Colab Link:
https://colab.research.google.com/drive/1alJNsalf87i5W8QV43TofT1Bnu505yde?usp=sharing

Error Message:
Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/SeargeSDXL/searge_sdxl_sampler_node.py", line 416, in load_vae
    return self.vae_loader.load_vae(vae_name)
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 557, in load_vae
    vae = comfy.sd.VAE(ckpt_path=vae_path)
  File "/content/drive/MyDrive/ComfyUI/comfy/sd.py", line 576, in __init__
    sd = utils.load_torch_file(ckpt_path)
  File "/content/drive/MyDrive/ComfyUI/comfy/utils.py", line 11, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 309, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

Thank you very much!

**Comment by rivaldophilip** [comment]
Fixed by redownloading the safetensor models
