### ISSUE TITLE
Can't get any sample workflows to run

### ISSUE THREAD

**Issue by Tikishark777** [SeargeDP/SeargeSDXL#65]
I receive the following errors when trying to run the sample workflow.  I downloaded all models when installing the pre-release 3.99 version.  Note: I tried to update to version 4.00, but the installer said that everything is already installed.  

Here's my console output:

!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\Users\John\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\John\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\John\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\John\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\magic_box.py", line 269, in process
    (data, stage_result) = self.run_stage(stage, data, stage_input)
  File "C:\Users\John\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\magic_box.py", line 248, in run_stage
    (data, stage_result) = stage_processor.process(data, stage_input)
  File "C:\Users\John\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\stage_sampling.py", line 126, in process
    latent = sampler(base_model, base_positive, base_negative, latent, seed, steps, cfg,
  File "C:\Users\John\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\node_wrapper.py", line 96, in sdxl_sampler
    result = sdxl_ksampler(base_model, refiner_model, noise_seed, base_steps, refiner_steps, cfg, sampler_name,
  File "C:\Users\John\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\custom_sdxl_ksampler.py", line 353, in sdxl_ksampler
    samples = sdxl_sample(base_model, refiner_model, noise, base_steps, refiner_steps, cfg, sampler_name, scheduler,
  File "C:\Users\John\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\custom_sdxl_ksampler.py", line 168, in sdxl_sample
    base_models, inference_memory = comfy.sample.get_additional_models(base_positive, base_negative,
TypeError: get_additional_models() takes 2 positional arguments but 3 were given

**Comment by SeargeDP** [comment]
You need to update your ComfyUI to a newer version

**Comment by Tikishark777** [comment]
That worked... Thank you!
