### ISSUE TITLE
4.0 Compatible with Stability Matrix?

### ISSUE THREAD

**Issue by PresTrembleyIIIEsq** [SeargeDP/SeargeSDXL#66]
My ComfyUI install on Linux (Manjaro) is managed by [Stability Matrix](https://github.com/LykosAI/StabilityMatrix). Earlier versions of SeargeSDXL worked just fine with this setup. However, today I went into the /ComfyUI/custom_nodes/SeargeSDXL folder and ran a `git pull` to update everything, but on loading the new 4.0 json workflow file, almost all of the nodes are red/errors.

Stability Matrix is fully updated. It doesn't show any available updates for ComfyUI, but if there's a way to check manually, I can try that.

I assume I'm just doing something dumb or missing a step somewhere, but I'm not sure where / what it is.

On first launching ComfyUI through Stability Matrix, I get the following errors. The GUI still loads, though, and some of the below errors are pointing to some SeargeSDXL-related files, so I assume something's going on on that side.

--

```
[...]
Adding extra search path diffusers /home/[myuser]/.config/StabilityMatrix/Models/Diffusers
Adding extra search path gligen /home/[myuser]/.config/StabilityMatrix/Models/GLIGEN
Adding extra search path vae_approx /home/[myuser]/.config/StabilityMatrix/Models/ApproxVAE
Traceback (most recent call last):
File "/home/[myuser]/.config/StabilityMatrix/Packages/ComfyUI/nodes.py", line 1596, in load_custom_node
module_spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in _call_with_frames_removed
File "/home/[myuser]/.config/StabilityMatrix/Packages/ComfyUI/custom_nodes/SeargeSDXL/init.py", line 33, in
from .modules._legacy import LEGACY_CLASS_MAPPINGS, LEGACY_DISPLAY_NAME_MAPPINGS
File "/home/[myuser]/.config/StabilityMatrix/Packages/ComfyUI/custom_nodes/SeargeSDXL/modules/init.py", line 29, in
from .ui import Defs
File "/home/[myuser]/.config/StabilityMatrix/Packages/ComfyUI/custom_nodes/SeargeSDXL/modules/ui.py", line 37, in
from .custom_sdxl_ksampler import CfgMethods
File "/home/[myuser]/.config/StabilityMatrix/Packages/ComfyUI/custom_nodes/SeargeSDXL/modules/custom_sdxl_ksampler.py", line 38, in
from comfy.model_management import get_torch_device, batch_area_memory, load_models_gpu
ImportError: cannot import name 'batch_area_memory' from 'comfy.model_management' (/home/[myuser]/.config/StabilityMatrix/Packages/ComfyUI/comfy/model_management.py)

Cannot import /home/[myuser]/.config/StabilityMatrix/Packages/ComfyUI/custom_nodes/SeargeSDXL module for custom nodes: cannot import name 'batch_area_memory' from 'comfy.model_management' (/home/[myuser]/.config/StabilityMatrix/Packages/ComfyUI/comfy/model_management.py)

Import times for custom nodes:
0.0 seconds (IMPORT FAILED): /home/[myuser]/.config/StabilityMatrix/Packages/ComfyUI/custom_nodes/SeargeSDXL

Starting server

To see the GUI go to: http://127.0.0.1:8188/
```

**Comment by SeargeDP** [comment]
I don't know anything about Stability Matrix, but it looks like it's not using the latest version of ComfyUI

**Comment by PresTrembleyIIIEsq** [comment]
That must have been it - I just wiped and re-installed ComfyUI, and now it's working again.

Thanks for putting all these together, by the way!
