### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by normusF7** [SeargeDP/SeargeSDXL#68]
I get Memory Error when running withe default parameters (16 GB RAM)

```Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "E:\Dev\AI\ComfyUI_windows_portable\ComfyUI\main.py", line 92, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "E:\Dev\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 375, in execute
    success, error, ex = recursive_execute(self.server, prompt, self.outputs, output_node_id, extra_data, executed, prompt_id, self.outputs_ui, self.object_storage)
  File "E:\Dev\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 134, in recursive_execute
    result = recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui, object_storage)
  File "E:\Dev\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 134, in recursive_execute
    result = recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui, object_storage)
  File "E:\Dev\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 134, in recursive_execute
    result = recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui, object_storage)
  [Previous line repeated 7 more times]
  File "E:\Dev\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 177, in recursive_execute
    output_data_formatted[node_id] = [[format_value(x) for x in l] for l in node_outputs]
  File "E:\Dev\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 177, in <listcomp>
    output_data_formatted[node_id] = [[format_value(x) for x in l] for l in node_outputs]
  File "E:\Dev\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 177, in <listcomp>
    output_data_formatted[node_id] = [[format_value(x) for x in l] for l in node_outputs]
  File "E:\Dev\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 117, in format_value
    return str(x)
MemoryError

**Comment by normusF7** [comment]
There was not enough space on the system disc.
