### ISSUE TITLE
4.1 issues with latest comfy ui?

### ISSUE THREAD

**Issue by SesioN** [SeargeDP/SeargeSDXL#79]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "g:\Python\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "g:\Python\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "g:\Python\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "G:\Python\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\magic_box.py", line 269, in process
    (data, stage_result) = self.run_stage(stage, data, stage_input)
  File "G:\Python\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\magic_box.py", line 248, in run_stage    (data, stage_result) = stage_processor.process(data, stage_input)
  File "G:\Python\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\stage_latent_inputs.py", line 127, in process
    (width, height) = get_mask_size(mask)
  File "G:\Python\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\utils.py", line 51, in get_mask_size
    (height, width) = mask.shape
ValueError: too many values to unpack (expected 2)

**Comment by radiantraptor** [comment]
I have the exact same errors when using inpaint. Text to image and image to image are working fine.

**Comment by SeargeDP** [comment]
Thanks for reporting this issue. I found the breaking change in ComfyUI and will update this custom node extension with a bug fix. 

If you are using the install script you can already test the change on the dev/test branch, just re-run the install script and select that branch when the question comes up. Just make sure to switch back to the stable release branch after the next version of my workflow is released.

**Comment by radiantraptor** [comment]
It's now working again, thank you very much for fixing this!

**Comment by SeargeDP** [comment]
Close as resolved
