### ISSUE TITLE
Error when loading the Nodes

### ISSUE THREAD

**Issue by MTHALO** [SeargeDP/SeargeSDXL#91]
This is the error it gave me I tried all of the recommended installations I don't know what I did wrong

When loading the graph, the following node types were not found:
SeargePreviewImage
SeargeTextInputV2
SeargeMagicBox
SeargeDebugPrinter
SeargePipelineTerminator
SeargeGenerationParameters
SeargeImageSaving
SeargeOperatingMode
SeargeImage2ImageAndInpainting
SeargeModelSelector
SeargeConditionMixing
SeargeCustomPromptMode
SeargeCustomAfterVaeDecode
SeargeSeparator
SeargeConditioningParameters
SeargeHighResolution
SeargeAdvancedParameters
SeargePromptStyles
SeargeCustomAfterUpscaling
SeargeUpscaleModels
SeargeLoras
SeargePipelineStart
SeargeImageAdapterV2
SeargePromptAdapterV2
SeargeControlnetModels
SeargeControlnetAdapterV2
SeargeFreeU
Nodes that have failed to load will show as red on the graph.

**Comment by JranZu** [comment]
Having the exact same issue after updating - even the old workflows are almost all red.

I installed it through ComfyUI Manager, made sure the directly was deleted from the custom nodes folder, and then reinstalled from the release on GitHub.  

![image](https://github.com/SeargeDP/SeargeSDXL/assets/3099474/204ed9f0-c8e5-406a-93e3-2846b412cf9e)

**Comment by JranZu** [comment]
I am getting this error in the console:

`Searge-SDXL v4.3 in D:\AI Tools\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
Traceback (most recent call last):
  File "D:\AI Tools\StableDiffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI Tools\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\__init__.py", line 35, in <module>
    from .searge_sdxl import SEARGE_CLASS_MAPPINGS, SEARGE_DISPLAY_NAME_MAPPINGS
  File "D:\AI Tools\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\searge_sdxl.py", line 54, in <module>
    from .modules.magic_box import SeargeMagicBox
  File "D:\AI Tools\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\magic_box.py", line 31, in <module>
    from .stage_pre_processing import SeargePreProcessData
  File "D:\AI Tools\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\stage_pre_processing.py", line 33, in <module>
    from .node_wrapper import NodeWrapper
  File "D:\AI Tools\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\node_wrapper.py", line 44, in <module>
    class NodeWrapper:
  File "D:\AI Tools\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\node_wrapper.py", line 52, in NodeWrapper
    freeu_v2 = comfy_extras.nodes_freelunch.FreeU_V2()
AttributeError: module 'comfy_extras.nodes_freelunch' has no attribute 'FreeU_V2'

Cannot import D:\AI Tools\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL module for custom nodes: module 'comfy_extras.nodes_freelunch' has no attribute 'FreeU_V2'`

**Comment by henry808** [comment]
I had the same exact issue. I tried an update all from the manager and restart and now it works.

**Comment by SeargeDP** [comment]
You have to also update ComfyUI to the latest version. FreeU v2 was recently added and if you are still running an older version of ComfyUI it won't work.

**Comment by lauriinc** [comment]
I also tried this for the first time today, downloaded the latest comfyui and used the installer but I'm only getting an error when trying to load the "Searge-SDXL-Reborn-v4_3" workflow file.

![comfy-error](https://github.com/SeargeDP/SeargeSDXL/assets/5120743/27e95ec5-f4d4-4e22-82b6-140ae2b2a9f4)
![installer](https://github.com/SeargeDP/SeargeSDXL/assets/5120743/fc8dc91d-4f67-4f96-9872-bda854416ec1)
