### ISSUE TITLE
import failed 

### ISSUE THREAD

**Issue by Autantpourmoi** [SeargeDP/SeargeSDXL#92]
hi since 2 or 3 days , i've got this import failed message only on seargesdxl custom nodes ...
Already reinstall it but no better results 
any idea as all other ones are ok 
Mac osx sonoma / last version of comfy ui

**Comment by jimihenrik** [comment]
@Autantpourmoi you could provide a little more details on what failed on the import.

But yeah, I have the same problem, I just installed this for the first time ever with the automatic install bat and on ComfyUI launch I get this 

```Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL\__init__.py", line 35, in <module>
    from .searge_sdxl import SEARGE_CLASS_MAPPINGS, SEARGE_DISPLAY_NAME_MAPPINGS
  File "C:\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL\searge_sdxl.py", line 54, in <module>
    from .modules.magic_box import SeargeMagicBox
  File "C:\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL\modules\magic_box.py", line 31, in <module>
    from .stage_pre_processing import SeargePreProcessData
  File "C:\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL\modules\stage_pre_processing.py", line 33, in <module>
    from .node_wrapper import NodeWrapper
  File "C:\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL\modules\node_wrapper.py", line 44, in <module>
    class NodeWrapper:
  File "C:\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL\modules\node_wrapper.py", line 52, in NodeWrapper
    freeu_v2 = comfy_extras.nodes_freelunch.FreeU_V2()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'comfy_extras.nodes_freelunch' has no attribute 'FreeU_V2'

Cannot import C:\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL module for custom nodes: module 'comfy_extras.nodes_freelunch' has no attribute 'FreeU_V2'```

**Comment by Autantpourmoi** [comment]
don't know why , did work perfectly fine today , i erased one custom nodes may be there was a conflict
