### ISSUE TITLE
ERROR when I try to generate an image with 4.3

### ISSUE THREAD

**Issue by henry808** [SeargeDP/SeargeSDXL#96]
Everything is updated and it did work for a while, but now I get this error when I try to generate an image:

Requested to load SDXL
Loading 1 new model
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\magic_box.py", line 269, in process
    (data, stage_result) = self.run_stage(stage, data, stage_input)
  File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\magic_box.py", line 248, in run_stage
    (data, stage_result) = stage_processor.process(data, stage_input)
  File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\stage_sampling.py", line 126, in process
    latent = sampler(base_model, base_positive, base_negative, latent, seed, steps, cfg,
  File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\node_wrapper.py", line 99, in sdxl_sampler
    result = sdxl_ksampler(base_model, refiner_model, noise_seed, base_steps, refiner_steps, cfg, sampler_name,
  File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\custom_sdxl_ksampler.py", line 356, in sdxl_ksampler
    samples = sdxl_sample(base_model, refiner_model, noise, base_steps, refiner_steps, cfg, sampler_name, scheduler,
  File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\custom_sdxl_ksampler.py", line 184, in sdxl_sample
    pos_base_copy = comfy.sample.convert_cond(base_positive)
AttributeError: module 'comfy.sample' has no attribute 'convert_cond'

This happened after I downloaded the optional models using the install script. Maybe one of those models does not work right?

**Comment by SeargeDP** [comment]
Can you make sure that ComfyUI is updated to the latest version and that you are using v4.3.1 of my extension and workflow? ComfyUI recently made a change that broke some of my code and I released v4.3.1 earlier today to fix that issue, but it requires ComfyUI to be updated as well.

**Comment by henry808** [comment]
Thanks. That fixed it!
